# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
    exclude: [ build/**, lib/**.freezed.dart, lib/**.g.dart, lib/src/localizations/**.dart ]
    language:
        strict-casts: true
        strict-raw-types: true

formatter:
    page_width: 120

linter:
    # The lint rules applied to this project can be customized in the
    # section below to disable rules from the `package:flutter_lints/flutter.yaml`
    # included above or to enable additional rules. A list of all available lints
    # and their documentation is published at https://dart.dev/lints.
    #
    # Instead of disabling a lint rule for the entire project in the
    # section below, it can also be suppressed for a single line of code
    # or a specific dart file by using the `// ignore: name_of_lint` and
    # `// ignore_for_file: name_of_lint` syntax on the line or in the file
    # producing the lint.
    rules:
        # https://github.com/flutter/packages/blob/main/packages/flutter_lints/lib/flutter.yaml
        # - avoid_print
        # - avoid_unnecessary_containers
        # - avoid_web_libraries_in_flutter
        # - no_logic_in_create_state
        # - prefer_const_constructors_in_immutables
        # - sized_box_for_whitespace
        # - sort_child_properties_last
        # - use_build_context_synchronously
        # - use_full_hex_values_for_flutter_colors
        # - use_key_in_widget_constructors
        # https://github.com/dart-lang/core/blob/main/pkgs/lints/lib/recommended.yaml
        # - annotate_overrides
        # - avoid_function_literals_in_foreach_calls
        # - avoid_init_to_null
        # - avoid_renaming_method_parameters
        # - avoid_return_types_on_setters
        # - avoid_returning_null_for_void
        # - avoid_single_cascade_in_expression_statements
        # - constant_identifier_names
        # - control_flow_in_finally
        # - empty_constructor_bodies
        # - empty_statements
        # - exhaustive_cases
        # - implementation_imports
        # - invalid_runtime_check_with_js_interop_types
        # - library_prefixes
        # - library_private_types_in_public_api
        # - no_leading_underscores_for_library_prefixes
        # - no_leading_underscores_for_local_identifiers
        # - null_closures
        # - overridden_fields
        # - package_names
        # - prefer_adjacent_string_concatenation
        # - prefer_collection_literals
        # - prefer_conditional_assignment
        # - prefer_contains
        # - prefer_final_fields
        # - prefer_for_elements_to_map_fromIterable
        # - prefer_function_declarations_over_variables
        # - prefer_if_null_operators
        # - prefer_initializing_formals
        # - prefer_inlined_adds
        # - prefer_interpolation_to_compose_strings
        # - prefer_is_not_operator
        # - prefer_null_aware_operators
        # - prefer_spread_collections
        # - recursive_getters
        # - slash_for_doc_comments
        # - type_init_formals
        # - unnecessary_brace_in_string_interps
        # - unnecessary_const
        # - unnecessary_constructor_name
        # - unnecessary_getters_setters
        # - unnecessary_late
        # - unnecessary_library_name
        # - unnecessary_new
        # - unnecessary_null_aware_assignments
        # - unnecessary_null_in_if_null_operators
        # - unnecessary_nullable_for_final_variable_declarations
        # - unnecessary_string_escapes
        # - unnecessary_string_interpolations
        # - unnecessary_this
        # - unnecessary_to_list_in_spreads
        # - unnecessary_underscores
        # - use_function_type_syntax_for_parameters
        # - use_rethrow_when_possible
        # - use_super_parameters
        # https://github.com/dart-lang/core/blob/main/pkgs/lints/lib/core.yaml
        # - avoid_empty_else
        # - avoid_relative_lib_imports
        # - avoid_shadowing_type_parameters
        # - avoid_types_as_parameter_names
        # - await_only_futures
        # - camel_case_extensions
        # - camel_case_types
        # - collection_methods_unrelated_type
        # - curly_braces_in_flow_control_structures
        # - dangling_library_doc_comments
        # - depend_on_referenced_packages
        # - empty_catches
        # - file_names
        # - hash_and_equals
        # - implicit_call_tearoffs
        # - library_annotations
        # - no_duplicate_case_values
        # - no_wildcard_variable_uses
        # - non_constant_identifier_names
        # - null_check_on_nullable_type_parameter
        # - prefer_generic_function_type_aliases
        # - prefer_is_empty
        # - prefer_is_not_empty
        # - prefer_iterable_whereType
        # - prefer_typing_uninitialized_variables
        # - provide_deprecation_message
        # - secure_pubspec_urls
        # - strict_top_level_inference
        # - type_literal_in_constant_pattern
        # - unintended_html_in_doc_comment
        # - unnecessary_overrides
        # - unrelated_type_equality_checks
        # - use_string_in_part_of_directives
        # - valid_regexps
        # - void_checks

        # Additional information about this file can be found at
        # https://dart.dev/guides/language/analysis-options

        always_declare_return_types: true
        always_put_required_named_parameters_first: true
        #        - always_specify_types
        always_use_package_imports: true
        annotate_redeclares: true
        avoid_annotating_with_dynamic: true
        avoid_bool_literals_in_conditional_expressions: true
        avoid_catches_without_on_clauses: true
        #avoid_catching_errors: true
        avoid_classes_with_only_static_members: true
        avoid_double_and_int_checks: true
        avoid_dynamic_calls: true
        avoid_equals_and_hash_code_on_mutable_classes: true
        avoid_escaping_inner_quotes: true
        avoid_field_initializers_in_const_classes: true
        #- avoid_final_parameters is incompatible with the rule 'prefer_final_parameters'
        avoid_futureor_void: true
        avoid_implementing_value_types: true
        avoid_js_rounded_ints: true
        avoid_multiple_declarations_per_line: true
        avoid_null_checks_in_equality_operators: true
        avoid_positional_boolean_parameters: true
        avoid_private_typedef_functions: true
        #- avoid_redundant_argument_values disable
        avoid_returning_this: true
        avoid_setters_without_getters: true
        avoid_slow_async_io: true
        avoid_type_to_string: true
        #- avoid_types_on_closure_parameters is incompatible with the rule 'always_specify_types'
        avoid_unused_constructor_parameters: true
        avoid_void_async: true
        cancel_subscriptions: true
        cascade_invocations: true
        cast_nullable_to_non_nullable: true
        close_sinks: true
        combinators_ordering: true
        comment_references: true
        conditional_uri_does_not_exist: true
        deprecated_consistency: true
        deprecated_member_use_from_same_package: true
        diagnostic_describe_all_properties: true
        directives_ordering: true
        discarded_futures: true
        do_not_use_environment: true
        #- document_ignores disable
        eol_at_end_of_file: true
        flutter_style_todos: true
        implicit_reopen: true
        invalid_case_patterns: true
        join_return_with_assignment: true
        leading_newlines_in_multiline_strings: true
        library_names: true
        #- lines_longer_than_80_chars disable
        literal_only_boolean_expressions: true
        matching_super_parameters: true
        missing_code_block_language_in_doc_comment: true
        missing_whitespace_between_adjacent_strings: true
        no_adjacent_strings_in_list: true
        no_default_cases: true
        no_literal_bool_comparisons: true
        no_runtimeType_toString: true
        no_self_assignments: true
        noop_primitive_operations: true
        #- omit_local_variable_types is incompatible with the rule 'always_specify_types'
        #- omit_obvious_local_variable_types is incompatible with the rule 'always_specify_types'
        #- omit_obvious_property_types is incompatible with the rule 'always_specify_types'
        one_member_abstracts: true
        only_throw_errors: true
        package_prefixed_library_names: true
        parameter_assignments: true
        prefer_asserts_in_initializer_lists: true
        prefer_asserts_with_message: true
        prefer_const_constructors: true
        prefer_const_declarations: true
        prefer_const_literals_to_create_immutables: true
        prefer_constructors_over_static_methods: true
        #- prefer_double_quotes is incompatible with the rule 'prefer_double_quotes'
        #- prefer_expression_function_bodies disable
        prefer_final_in_for_each: true
        prefer_final_locals: true
        prefer_final_parameters: true
        prefer_foreach: true
        prefer_if_elements_to_conditional_expressions: true
        prefer_int_literals: true
        prefer_mixin: true
        prefer_null_aware_method_calls: true
        #- prefer_relative_imports is incompatible with the rule 'always_use_package_imports'
        prefer_single_quotes: true
        prefer_void_to_null: true
        #- public_member_api_docs disable
        require_trailing_commas: true
        sized_box_shrink_expand: true
        sort_constructors_first: true
        sort_pub_dependencies: true
        sort_unnamed_constructors_first: true
        specify_nonobvious_local_variable_types: true
        specify_nonobvious_property_types: true
        test_types_in_equals: true
        throw_in_finally: true
        tighten_type_of_initializing_formals: true
        type_annotate_public_apis: true
        unawaited_futures: true
        unnecessary_async: true
        #- unnecessary_await_in_return disable
        unnecessary_breaks: true
        #- unnecessary_final is incompatible with the rule 'prefer_final_locals'
        unnecessary_lambdas: true
        unnecessary_library_directive: true
        unnecessary_null_aware_operator_on_extension_on_nullable: true
        unnecessary_null_checks: true
        unnecessary_parenthesis: true
        unnecessary_raw_strings: true
        unnecessary_statements: true
        unreachable_from_main: true
        unsafe_variance: true
        use_colored_box: true
        use_decorated_box: true
        use_enums: true
        use_if_null_to_convert_nulls_to_bools: true
        use_is_even_rather_than_modulo: true
        use_late_for_private_fields_and_variables: true
        use_named_constants: true
        use_raw_strings: true
        use_setters_to_change_properties: true
        use_string_buffers: true
        use_test_throws_matchers: true
        use_to_and_as_if_applicable: true
        use_truncating_division: true

        always_put_control_body_on_new_line: false
        empty_catches: false
