name: infra
description: ''
publish_to: none
resolution: workspace
version: 1.0.0+1

environment:
    sdk: '>=3.6.0 <5.0.0'

dependencies:
    collection: any
    flutter: { sdk: flutter }
    flutter_localizations: { sdk: flutter }
    freezed_annotation: any
    safe_change_notifier: any
    shared_preferences: any
dev_dependencies:
    build_runner: any
    flutter_lints: ^5.0.0
    flutter_test: { sdk: flutter }
    freezed: any
